name: Style Guide Compliance Check
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
    branches:
      - "main"
jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    env:
      USER: "pavelpiha"
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      ANTHROPIC_API_KEY: ${{secrets.PAVEL_EPAM}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: |
          cd ./.github/scripts
          npm install
      - name: Run Script
        run: |
          node ./.github/scripts/dist/main.js
